### ISSUE TITLE
Unable to send SMS on Lineage 21

### ISSUE THREAD

**Issue by GC55Gith** [8890q/android_device_samsung_dreamlte#2]
Hello Ivan Meler,
I and others could not send SMS. I'm not sur if this was already a problem with Lineageos 20 ...
I have attached the Logcat file ...
Thank's for all the great work!

Greetings from Germany
[
[logcat.txt](https://github.com/8890q/android_device_samsung_dreamlte/files/14313177/logcat.txt)
](url)

**Comment by ivanmeler** [comment]
Thanks for the report, fixed with https://github.com/8890q/android_device_samsung_universal8895-common/commit/b79bb3fdd783eb7983754f70966092013c13c9ee
updated builds will be out in next 24h
